### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by patrick-kinsella-rf** [oasis-open/cti-taxii-client#119]
Possible to update to support basic auth?

`Token` would need to be `Basic`:
https://github.com/oasis-open/cti-taxii-client/blob/54dabadf1a67517e99e6a8f2961614a2a4f5ad2c/taxii2client/common.py#L143

**Comment by andrewbeard** [comment]
You don't need to add it, it's already there. The TokenAuth object implements an authentication type that isn't supported by the underlying requests library, but the HTTPBasicAuth module (already part of requests) does exactly what you want.
https://requests.readthedocs.io/en/latest/user/authentication/

You can even see it being used as part of the existing code here:
https://github.com/oasis-open/cti-taxii-client/blob/54dabadf1a67517e99e6a8f2961614a2a4f5ad2c/taxii2client/common.py#L267

**Comment by patrick-kinsella-rf** [comment]
Thank you Andrew, this worked great! I didn't realize what I already had. Closing this issue
