### ISSUE TITLE
Allow Configurable STIX Version

### ISSUE THREAD

**Issue by jasonumd** [oasis-open/cti-taxii-client#15]
The TAXII server response is now "application/vnd.oasis.stix+json; version=2.1". Client library code is looking for "application/vnd.oasis.stix+json; version=2.0".

**Comment by rpiazza** [comment]
Bret sent some mail at 8:49.  Does that address this issue?

**Comment by gtback** [comment]
For context, the TAXII server being discussed here is https://test.freetaxii.com:8000/taxii/

See my response [here](https://lists.oasis-open.org/archives/cti-users/201711/msg00017.html):

> I don’t think it’s a bug for the taxii client library to reject a response with STIX 2.1 content type when it asked for STIX 2.0. It would certainly be a valid feature request that the library allow you to configure what version you are asking for, though. :-)

**Comment by jasonumd** [comment]
You're very right Greg, my mistake. Definitely not a bug to reject a mismatched connection.

**Comment by gtback** [comment]
I'll just consider this a feature request then 😀 . I changed the title. If you have time and are interested in helping with this, I'd be happy to walk you through the process.

**Comment by gtback** [comment]
One other note, for whoever ends up implementing this. Even if freetaxii is returning STIX 2.1, the default for the TAXII library should be 2.0 until STIX 2.1 is at least a committee specification.

**Comment by emmanvg** [comment]
Is this related to #21?

**Comment by rpiazza** [comment]
I think so
