### ISSUE TITLE
timeline on completion of libtaxii

### ISSUE THREAD

**Issue by vinayreddy123** [oasis-open/cti-taxii-client#2]
I'm interested in using cti-taxii-client. Is it possible to estimate when the majority of the implementation will be completed?

Thanks!

**Comment by gtback** [comment]
Hi, @vinayreddy123, I'm hoping we get basic functionality for all of the TAXII endpoints completed in the next week or so. Some of the more advanced features (like pagination) will likely take longer, but should still be in the next few weeks.
