### ISSUE TITLE
Only use UTF-8 strings when POSTing to the server

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-taxii-client#22]
This occurs in 2 places:

1.	`taxii2client._HTTPConnection.post()` should use **`requests.post(data=X)`** rather than requests.post(json=X). This function is called from `taxii2client.Collection.add_objects()`. **X should be a UTF-8 encoded byte string**.
    - If we use ‘data’ and X is a dict, it will be form-encoded, which we don’t want.
    - If we use ‘json=X’ and X is a dict, requests will call `json.dumps()`, which is OK but means we can’t pass dicts containing datetime objects or anything else that isn’t JSON-serializeable (such as _STIXBase objects). 
    - Note that we control this, so we don’t need to do anything to address other types in this function.
2.	`taxii2client.Collection.add_objects(X)` should **prefer to accept a Unicode string**, which it **encodes as UTF-8** before passing to requests (urllib3, which requests uses internally, wants a bytes-like object). 
    - This string **should be a valid STIX 2 bundle**, but we don’t want to do anything in the TAXII library to validate this. This will improve performance compared to validating ourselves. We prefer to receive this from somewhere that has already done the validation (python-stix2). The server should do its own validation, and we can catch errors and return them to the client, but we don’t want to try to validate ourselves ahead of time.
    - If X is already a bytestring, we pass it unmodified. We shouldn’t try to detect the encoding, but be aware that servers might reject the content if it’s not in UTF-8.
    - If X is a dict, we call `json.dumps()`, which returns a Unicode string, that we then encode as UTF-8. ~We can do some trivial conversions in a custom JSON encoder, like detecting datetimes and converting to `isoformat()`, but~ The TAXII client shouldn’t have any knowledge of STIX 2 when doing this encoding (which is part of why we prefer having a string that has already been converted from a dict to JSON).

**Comment by clenk** [comment]
Related to https://github.com/oasis-open/cti-python-stix2/issues/134.

**Comment by emmanvg** [comment]
On the third bullet of `taxii2client.Collection.add_objects(X)`:<br>
I don't like the custom` JSONEncoder` and `isoformat()` idea because we might introduce problems when converting data with different restrictions on the precision after the seconds. I could do `json.dumps(bundle, encoding='utf-8')` when `isinstance(bundle, dict)` is True

**Comment by gtback** [comment]
I'm fine with not supporting `datetime`s (which is the primary use case for a custom `JSONEncoder`). `datetime` objects are the most straightforward data type which is not JSON serializable by default, but has a pretty straightforward encoding anyway (`isoformat`). That doesn't mean we should burden cti-taxii-client with this complexity though. As we've said elsewhere, when coming from `stix2` objects, the TAXIICollectionSink will handle serializing to a string. Other uses of the TAXII client outside python-stix2 will likely involve building dictionaries from scratch and/or parsing existing STIX 2 and making minor changes; in either case, it's not unreasonable to expect users of cti-taxii-client to handle proper JSON encoding for their STIX content.
