### ISSUE TITLE
Pagination Implementation

### ISSUE THREAD

**Issue by ajnovice** [oasis-open/cti-taxii-client#23]
I didn't find any implementation for Pagination.
Do I have to implement the code for pagination or is there any other way?

**Comment by gtback** [comment]
Right now, this library doesn't handle pagination, but I would absolutely accept a pull request that adds it. 

I haven't really thought through an implementation approach; I've used libraries like the various GitHub API ones that do this. We probably don't want to *always* return all the items from every page, but make it easy to fetch them on demand when iterating through the results, for instance. What do you think, @AjayS91 ?

**Comment by AjayS91** [comment]
I would love to do that and I also identified some minor bugs. First, I would fix the bugs in the coming weekend.

**Comment by gtback** [comment]
Thanks, @AjayS91. That sounds good. We are currently working on fixes to #22 and #24, but if you have found other bugs, fixing them would be very much appreciated! 💯

**Comment by gtback** [comment]
Also, in case you weren't aware, you'll need to complete the [OASIS CLA form](https://www.oasis-open.org/resources/open-repositories/cla) prior to any pull requests getting merged. Thanks again!

**Comment by robincover** [comment]
Ajay's CLA is on file.  Thanks Greg and Ajay. -rcc
