### ISSUE TITLE
Provide access to raw TAXII responses

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-taxii-client#39]
This can probably be behind some sort of "private" interface (like `_raw`), but it would be helpful to have access to the raw JSON bodies on returned responses.

**Comment by chisholm** [comment]
To clarify, I think this means that the endpoint classes should have a "_raw" attribute, which is set to the parsed JSON its instances were created from.  This doesn't account for all responses though.  The ApiRoot class is constructed from the API Root Information endpoint (TAXII 2.0 spec section 4.2), but adds collection metadata from the Get Collections endpoint as well (section 5.1).  I guess the "_raw" attribute of ApiRoot should return the former, not the latter?  (The Collection class would return info about one collection (section 5.2), so the 5.1 info isn't covered there.)

In general, I think the feasibility of this will depend on how straightforwardly the API maps to the spec endpoints.  It's pretty simple now, but who knows how it will evolve.
