### ISSUE TITLE
Clarification:  Is this installable via pip?

### ISSUE THREAD

**Issue by packet-rat** [oasis-open/cti-taxii-client#4]
Seems to be contradictory info:

"Installation
The easiest way to install the TAXII client is with pip:
```
$ pip install taxii2_client
```
The cti-taxii-client is not currently available on pip."

```
pip install taxii2_client
Collecting taxii2_client
  Could not find a version that satisfies the requirement taxii2_client (from versions: )
No matching distribution found for taxii2_client
```

**Comment by gtback** [comment]
`taxii2-client` is now [available on PyPI](https://pypi.python.org/pypi/taxii2-client)
