### ISSUE TITLE
Figure out how to support TAXII 2.1

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-taxii-client#41]
Hopefully we can support all versions simultaneously, but we could also support different versions of the spec in different versions of the client. This may mean sending multiple media types in the accept header.

**Comment by emmanvg** [comment]
Took same approach as the one in `stix2` to support different versions simultaneously. All components from TAXII 2.0 live under `v20` similarly for TAXII 2.1 as `v21`. Shared structures moved into `common.py`. The clients will not send multiple media types and each expect a response based on the specific version of the specification.
