### ISSUE TITLE
Create ReadTheDocs page for project

### ISSUE THREAD

**Issue by emmanvg** [oasis-open/cti-taxii-client#42]

**Comment by emmanvg** [comment]
@gtback, I managed to create the ReadTheDocs site for [taxii2client](http://taxii2client.readthedocs.io/en/latest/). Although, I am getting a message saying `This repository doesn't have a valid webhook set up, commits won't trigger new builds for this project. 
See your project integrations for more information.` I don't have access to the repo settings so I can't configure the webhook.

**Comment by gtback** [comment]
The webhook is set up now (thanks @robincover !) . There's already some documentation. Do we want to add any more before considering this done?

**Comment by emmanvg** [comment]
I don't have anything else in mind that we could add...

**Comment by gtback** [comment]
Sounds good! Let's call this done then.
