### ISSUE TITLE
_HTTPConnection unexpected argument proxies

### ISSUE THREAD

**Issue by thangld322** [oasis-open/cti-taxii-client#48]
Hi,
I want to connect to TAXII server through a proxy so I use this:

> http_conn = _HTTPConnection(proxies=proxies)

But it returns a warning "Unexpected argument proxies".
I checked out its code and the init function is:
`def __init__(self, user=None, password=None, verify=True):`
No proxies.
So how can I use this through a proxy please?
Thankx

**Comment by clenk** [comment]
The proxy option is new and hasn't been included in a new PyPI release yet. Can you try installing from the Github master branch and see if the issue still exists? We'll have a new version out soon.

**Comment by thangld322** [comment]
Thanks @clenk ,
It worked!
