### ISSUE TITLE
Set timeout when get_objects()

### ISSUE THREAD

**Issue by thangld322** [oasis-open/cti-taxii-client#49]
Hi,
Thanks for such great tool.
I use this tool to connect to a TAXII server.
I can get root_api and collections succesfully. 
But when I use get_objects() to get objects, after about 30 second, it closes connection.
I try to `curl` the get objects API and it does response after quite a long time. 
So how can set timeout for cti-taxii-client when get objects so I can wait for a longer time?
Thanks so much.

**Comment by clenk** [comment]
Hi @thangld322. The client doesn't set any timeouts, and the `requests` library it uses under the hood by default just hangs until it gets a response. Is there any chance something else in your environment might cause this?

I tested this with a taxii server I modified to wait for several minutes before returning results, and the client still received them after the delay.

**Comment by thangld322** [comment]
Thanks for responding @clenk ,
I don't know what causes the timeout but I fixed the server to respond quick enough and everything is fine now.

**Comment by NguyenKyThinh94** [comment]
I have same problem.
Taxii server have some error collection, Server don't return data when i poll from. And taxii client being waitting stataus in 5 day.
Taxii client 1.1 have timeout, i can config by timeout parameter. But in taxii client 2.1 we can not.
