### ISSUE TITLE
Server() function doesn't return when using both user:password and proxies

### ISSUE THREAD

**Issue by thangld322** [oasis-open/cti-taxii-client#51]
My company server connects to internet through http proxy: 192.168.5.8:3128
I'm trying to feed data from [limo](https://limo.anomali.com/api/v1/taxii2/taxii/)
When I try it with curl command, it works:
`curl -x http://192.168.5.8:3128 --user guest:guest -k https://limo.anomali.com/api/v1/taxii2/taxii/`

> {"api_roots": ["https://limo.anomali.com/api/v1/taxii2/feeds/", "https://limo.anomali.com/api/v1/taxii2/trusted_circles/", "https://limo.anomali.com/api/v1/taxii2/search_filters/"], "contact": "info@anomali.com", "default": "https://limo.anomali.com/api/v1/taxii2/feeds/", "description": "TAXII 2.0 Server (guest)", "title": "ThreatStream Taxii 2.0 Server"}

But when I use cti-taxii-client, it doesn't return anything.
```
api_user = "guest"
api_password = "guest"
taxii_domain = "https://limo.anomali.com/api/v1/taxii2/taxii"
proxy = "192.168.5.8:3128"
proxies = {
            'http': proxy
        }
        http_conn = _HTTPConnection(proxies=proxies, user=api_user, password=api_password, verify=False)
        server_discovery = Server(url=taxii_domain, conn=http_conn)
```
What am I doing wrong here? Please help. Thank you!

**Comment by clenk** [comment]
I was unable to reproduce your issue, but do you need to add `http://` to the `proxy` variable? Another thing you could try is setting the HTTP_PROXY environment variable. We pass the `proxies` argument to `requests.session`, so [its documentation on proxies](http://docs.python-requests.org/en/master/user/advanced/#proxies) applies here too.

**Comment by thangld322** [comment]
Hi clenk,
My code here: 
```
from taxii2client import Server
from taxii2client import Collection, _HTTPConnection


def get_collection_threat_intelligence():
    # request to taxii server
    api_user = "guest"
    api_password = "guest"
    taxii_domain = "https://limo.anomali.com/api/v1/taxii2/taxii/"
    proxy = "http://192.168.5.8:3128"
    proxies = {
        'http': proxy,
        'https': proxy
    }
    http_conn = _HTTPConnection(proxies=proxies, user=api_user, password=api_password, verify=False)
    server_discovery = Server(url=taxii_domain, conn=http_conn)
    # get api_root
    api_root = server_discovery.api_roots[0]
    # get collections
    print(api_root.collections)
    data = []
    for collection in api_root.collections:
        if collection.can_read:
            temp = {
                'id': collection.id,
                'title': collection.title
            }
            data.append(temp)
    # return collections
    result = {
        'data': data
    }
    return result


if __name__ == "__main__":
    result = get_collection_threat_intelligence()

```
When I debug to this line `print(api_root.collections)`, it runs forever and never returns anything.
Again, curl works fine.
`curl --user guest:guest -k -x http://192.168.5.8:3128 https://limo.anomali.com/api/v1/taxii2/feeds/collections/`

**Comment by emmanvg** [comment]
@thangld322, the reason why your request fails in `print(api_root.collections)` is because ApiRoot objects are creating new Sessions that do not contain the proxies. What I could do is expose the proxies to `Server` and `ApiRoot`.

After that is done, you could do the following:
``` python
from taxii2client import Server
from taxii2client import Collection, _HTTPConnection


def get_collection_threat_intelligence():
    # request to taxii server
    api_user = "guest"
    api_password = "guest"
    taxii_domain = "https://limo.anomali.com/api/v1/taxii2/taxii/"
    proxy = "http://192.168.5.8:3128"
    proxies = {
        'http': proxy,
        'https': proxy
    }
    server_discovery = Server(url=taxii_domain, proxies=proxies, user=api_user, password=api_password, verify=False)
    # get api_root
    api_root = server_discovery.api_roots[0]
    # get collections
    print(api_root.collections)
    data = []
    for collection in api_root.collections:
        if collection.can_read:
            temp = {
                'id': collection.id,
                'title': collection.title
            }
            data.append(temp)
    # return collections
    result = {
        'data': data
    }
    return result


if __name__ == "__main__":
    result = get_collection_threat_intelligence()

```

Note that there is an ongoing issue related to how this should be done in #37. For now, I think we are ok with this change, but it is something that could change in the future as we shape the API.
