### ISSUE TITLE
ERROR - _populate_fields() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by thangld322** [oasis-open/cti-taxii-client#53]
```
server = Server(url, user=self.conf_api["user"], password=self.conf_api["password"], verify=False)
api_root = server.api_roots[0]
collections = api_root.collections
```
These code lines return this exceptions:

> ERROR - _populate_fields() got an unexpected keyword argument 'type'

When I use curl, server returns like this:

> {"collections": [{"can_read": true, "can_write": false, "description": "This data collection is for collecting malicious domains", "id": "861ecee6-09af-4cc9-8f80-8c6eac8bb5a4", "media_types": ["application/vnd.oasis.stix+json; version=2.0"], "title": "Indicator Domain Collection", "type": "domain"}]}

This error happens when we add a new field to collection `"type": "domain"`. But STIX standards allow us to custom collection fields.
Can you fix this? Thank you so much!

**Comment by emmanvg** [comment]
@thangld322 thanks for reporting this. What I have done is to be more flexible with the `populate_fields()` method. Any property not captured via the optional arguments will end up in the `custom_properties` property. Thus, in a future release you would access your content like so:

``` python
server = Server(url, user=self.conf_api["user"], password=self.conf_api["password"], verify=False)
api_root = server.api_roots[0]
collections = api_root.collections
print(collections.custom_properties["type"])
```
