### ISSUE TITLE
how to generate stix2 data for taxii2 server

### ISSUE THREAD

**Issue by dipenpatel235** [oasis-open/cti-taxii-client#58]

**Comment by dipenpatel235** [comment]
Hello,

i am trying to generate stix2 data using the below link
https://oasis-open.github.io/cti-documentation/examples/identifying-a-threat-actor-profile

then upload the same stix2 data into taxii2 server.
Now when i am trying to fetch the data from taxii2 client, it did not get any data although the data is already saved in server side.

this is method i am using for fetch data from server side
_from taxii2client import Collection
collection = Collection('https://example.com/api1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116')
collection.get_object('indicator--252c7c11-daf2-42bd-843b-be65edca9f61')_
(from this link: https://github.com/oasis-open/cti-taxii-client)

Below data is default data provided by taxii2 server
{
    "/discovery": {
        "title": "Some TAXII Server",
        "description": "This TAXII Server contains a listing of...",
        "contact": "string containing contact information",
        "default": "http://0.0.0.0:5000/api2/",
        "api_roots": [
            "http://0.0.0.0:5000/api1/",
            "http://0.0.0.0:5000/api2/",
            "http://0.0.0.0:5000/trustgroup1/"
        ]
    },
    "api1": {
        "information": {
            "title": "General STIX 2.0 Collections",
            "description": "A repo for general STIX data.",
            "versions": [
                "taxii-2.0"
            ],
            "max_content_length": 9765625
        },
        "status": {

        },
        "collections": [
        ]
    },
    "api2": {
        "information": {
            "title": "STIX 2.0 Indicator Collections",
            "description": "A repo for general STIX data.",
            "versions": [
                "taxii-2.0"
            ],
            "max_content_length": 9765625
        },
        "status": [
        ],
        "collections": [
        ]
    },
    "trustgroup1": {
        "information": {
            "title": "Malware Research Group",
            "description": "A trust group setup for malware researchers",
            "versions": [
                "taxii-2.0"
            ],
            "max_content_length": 9765625
        },
        "status": [
            {
                "id": "2d086da7-4bdc-4f91-900e-d77486753710",
                "status": "pending",
                "request_timestamp": "2016-11-02T12:34:34.12345Z",
                "total_count": 4,
                "success_count": 1,
                "successes": [
                    "indicator--a932fcc6-e032-176c-126f-cb970a5a1ade"
                ],
                "failure_count": 1,
                "failures": [
                    {
                        "id": "malware--664fa29d-bf65-4f28-a667-bdb76f29ec98",
                        "message": "Unable to process object"
                    }
                ],
                "pending_count": 2,
                "pendings": [
                    "indicator--252c7c11-daf2-42bd-843b-be65edca9f61",
                    "relationship--045585ad-a22f-4333-af33-bfd503a683b5"
                ]
            },
            {
                "id": "2d086da7-4bdc-4f91-900e-f4566be4b780",
				"status": "pending",
				"request_timestamp": "2016-11-02T12:34:34.12345Z",
                "total_objects": 2,
				"success_count": 0,
				"successes": [
                ],
				"failure_count": 0,
				"failures": [
                ],
				"pending_count": 0,
				"pendings": [
                ]
            }
        ],
        "collections": [
            {
                "id": "91a7b528-80eb-42ed-a74d-c6fbd5a26116",
                "title": "High Value Indicator Collection",
                "description": "This data collection is for collecting high value IOCs",
                "can_read": true,
                "can_write": true,
                "media_types": [
                    "application/vnd.oasis.stix+json; version=2.0"
                ],
                "objects": [
                    {
                        "created": "2017-01-27T13:49:53.997Z",
                        "description": "Poison Ivy",
                        "id": "malware--fdd60b30-b67c-11e3-b0b9-f01faf20d111",
                        "labels": [
                            "remote-access-trojan"
                        ],
                        "modified": "2017-01-27T13:49:53.997Z",
                        "name": "Poison Ivy",
                        "type": "malware"
                    },
                    {
                        "created": "2014-05-08T09:00:00.000Z",
                        "id": "indicator--a932fcc6-e032-176c-126f-cb970a5a1ade",
                        "labels": [
                            "file-hash-watchlist"
                        ],
                        "modified": "2014-05-08T09:00:00.000Z",
                        "name": "File hash for Poison Ivy variant",
                        "pattern": "[file:hashes.'SHA-256' = 'ef537f25c895bfa782526529a9b63d97aa631564d5d789c2b765448c8635fb6c']",
                        "type": "indicator",
                        "valid_from": "2014-05-08T09:00:00.000000Z"
                    },
                    {
                        "created": "2014-05-08T09:00:00.000Z",
                        "id": "relationship--2f9a9aa9-108a-4333-83e2-4fb25add0463",
                        "modified": "2014-05-08T09:00:00.000Z",
                        "relationship_type": "indicates",
                        "source_ref": "indicator--a932fcc6-e032-176c-126f-cb970a5a1ade",
                        "target_ref": "malware--fdd60b30-b67c-11e3-b0b9-f01faf20d111",
                        "type": "relationship"
                    }
                ],
                "manifest": [
                    {
                        "id": "indicator--a932fcc6-e032-176c-126f-cb970a5a1ade",
                        "date_added": "2016-11-01T03:04:05Z",
                        "versions": [
                            "2014-05-08T09:00:00.000Z"
                        ],
                        "media_types": [
                            "application/vnd.oasis.stix+json; version=2.0"
                        ]
                    },
                    {
                        "id": "malware--fdd60b30-b67c-11e3-b0b9-f01faf20d111",
                        "date_added": "2017-01-27T13:49:53.997Z",
                        "versions": [
                            "2017-01-27T13:49:53.997Z"
                        ],
                        "media_types": [
                            "application/vnd.oasis.stix+json; version=2.0"
                        ]
                    }
                ]
            },
            {
                "id": "52892447-4d7e-4f70-b94d-d7f22742ff63",
                "title": "Indicators from the past 24-hours",
                "description": "This data collection is for collecting current IOCs",
                "can_read": true,
                "can_write": false,
                "media_types": [
                    "application/vnd.oasis.stix+json; version=2.0"
                ],
                "objects": [
                    {
                        "created": "2016-11-03T12:30:59.000Z",
                        "id": "indicator--d81f86b9-975b-bc0b-775e-810c5ad45a4f",
                        "labels": [
                            "url-watchlist"
                        ],
                        "modified": "2017-01-27T13:49:53.935Z",
                        "name": "Malicious site hosting downloader",
                        "pattern": "[url:value = 'http://x4z9arb.cn/4712']",
                        "type": "indicator",
                        "valid_from": "2016-11-03T12:30:59.000Z"
                    },
					{
                        "created": "2016-11-03T12:30:59.000Z",
                        "description": "Accessing this url will infect your machine with malware.",
						"id": "indicator--d81f86b9-975b-bc0b-775e-810c5ad45a4f",
                        "labels": [
                            "url-watchlist"
                        ],
                        "modified": "2016-11-03T12:30:59.000Z",
                        "name": "Malicious site hosting downloader",
                        "pattern": "[url:value = 'http://x4z9arb.cn/4712']",
                        "type": "indicator",
                        "valid_from": "2017-01-27T13:49:53.935382Z"
                    }
                ],
                "manifest": [
                    {
                        "id": "indicator--d81f86b9-975b-bc0b-775e-810c5ad45a4f",
                        "date_added": "2016-12-27T13:49:53Z",
                        "versions": [
                            "2016-11-03T12:30:59.000Z",
                            "2017-01-27T13:49:53.935Z"
                        ],
                        "media_types": [
                            "application/vnd.oasis.stix+json; version=2.0"
                        ]
                    }
                ]
            },
            {
                "id": "64993447-4d7e-4f70-b94d-d7f33742ee63",
                "title": "Secret Indicators",
                "description": "Non accessilble",
                "can_read":false,
                "can_write": false,
                "media_types": [
                    "application/vnd.oasis.stix+json; version=2.0"
                ],
                "objects": [
                    {
                        "created": "2016-11-03T12:30:59.000Z",
                        "description": "Accessing this url will infect your machine with malware.",
                        "id": "indicator--b81f86b9-975b-bb0b-775e-810c5bd45b4f",
                        "labels": [
                            "url-watchlist"
                        ],
                        "modified": "2016-11-03T12:30:59.000Z",
                        "name": "Malicious site hosting downloader",
                        "pattern": "[url:value = 'http://z4z10farb.cn/4712']",
                        "type": "indicator",
                        "valid_from": "2017-01-27T13:49:53.935382Z"
                    }
                ],
                "manifest": [
                    {
                        "id": "indicator--b81f86b9-975b-bb0b-775e-810c5bd45b4f",
                        "date_added": "2016-12-27T13:49:53Z",
                        "versions": [
                            "2016-11-03T12:30:59.000Z",
                            "2017-01-27T13:49:53.935Z"
                        ],
                        "media_types": [
                            "application/vnd.oasis.stix+json; version=2.0"
                        ]
                    }
                ]
            }
        ]
    }
}


now i am adding the new data generated by stix2
{
    "spec_version": "2.0",
    "objects": [
      {
        "name": "Poison Ivy",
        "created": "2017-01-27T13:49:53.997Z",
        "labels": [
          "remote-access-trojan"
        ],
        "modified": "2017-01-27T13:49:53.997Z",
        "type": "malware",
        "id": "malware--fdd60b30-b67c-11e3-b0b9-f01faf20d111",
        "description": "Poison Ivy"
      },
      {
        "valid_from": "2014-05-08T09:00:00.000000Z",
        "name": "File hash for Poison Ivy variant",
        "created": "2014-05-08T09:00:00.000Z",
        "pattern": "[file:hashes.'SHA-256' = 'ef537f25c895bfa782526529a9b63d97aa631564d5d789c2b765448c8635fb6c']",
        "labels": [
          "file-hash-watchlist"
        ],
        "modified": "2014-05-08T09:00:00.000Z",
        "type": "indicator",
        "id": "indicator--a932fcc6-e032-176c-126f-cb970a5a1ade"
      },
      {
        "created": "2014-05-08T09:00:00.000Z",
        "modified": "2014-05-08T09:00:00.000Z",
        "target_ref": "malware--fdd60b30-b67c-11e3-b0b9-f01faf20d111",
        "relationship_type": "indicates",
        "type": "relationship",
        "id": "relationship--2f9a9aa9-108a-4333-83e2-4fb25add0463",
        "source_ref": "indicator--a932fcc6-e032-176c-126f-cb970a5a1ade"
      },
      {
        "name": "Teddy Bear",
        "created": "2019-06-24T04:38:11.014Z",
        "labels": [
          "nation-state"
        ],
        "resource_level": "government",
        "modified": "2019-06-24T04:38:11.014Z",
        "goals": [
          "compromising environment NGOs",
          "water-hole attacks geared towards energy sector"
        ],
        "sophistication": "innovator",
        "type": "threat-actor",
        "id": "threat-actor--d881bb22-bb8f-4a58-9c44-d26db3592979"
      },
      {
        "valid_from": "2019-06-24T04:38:11.015525Z",
        "name": "File hash for malware variant",
        "created": "2019-06-24T04:38:11.015Z",
        "pattern": "[file:hashes.md5 = 'd41d8cd98f00b204e9800998ecf8427e']",
        "labels": [
          "malicious-activity"
        ],
        "modified": "2019-06-24T04:38:11.015Z",
        "type": "indicator",
        "id": "indicator--2ca58eaf-fa1d-4341-bf56-8173ade40ba1"
      },
      {
        "name": "Teddy Bear",
        "created": "2019-06-24T04:38:36.140Z",
        "labels": [
          "nation-state"
        ],
        "resource_level": "government",
        "modified": "2019-06-24T04:38:36.140Z",
        "goals": [
          "compromising environment NGOs",
          "water-hole attacks geared towards energy sector"
        ],
        "sophistication": "innovator",
        "type": "threat-actor",
        "id": "threat-actor--a55ef562-6fec-4bb5-88ec-310ab560f512"
      },
      {
        "valid_from": "2019-06-24T04:38:36.141268Z",
        "name": "File hash for malware variant",
        "created": "2019-06-24T04:38:36.141Z",
        "pattern": "[file:hashes.md5 = 'd41d8cd98f00b204e9800998ecf8427e']",
        "labels": [
          "malicious-activity"
        ],
        "modified": "2019-06-24T04:38:36.141Z",
        "type": "indicator",
        "id": "indicator--ac2b637f-57d9-44eb-931d-dac666cc320b"
      },
      {
        "name": "Teddy Bear",
        "created": "2019-06-24T04:43:24.774Z",
        "labels": [
          "nation-state"
        ],
        "resource_level": "government",
        "modified": "2019-06-24T04:43:24.774Z",
        "goals": [
          "compromising environment NGOs",
          "water-hole attacks geared towards energy sector"
        ],
        "sophistication": "innovator",
        "type": "threat-actor",
        "id": "threat-actor--6b6c2c5b-a77d-4c5c-8251-0d5dfb5dd1f2"
      },
      {
        "valid_from": "2019-06-24T04:43:24.775746Z",
        "name": "File hash for malware variant",
        "created": "2019-06-24T04:43:24.775Z",
        "pattern": "[file:hashes.md5 = 'd41d8cd98f00b204e9800998ecf8427e']",
        "labels": [
          "malicious-activity"
        ],
        "modified": "2019-06-24T04:43:24.775Z",
        "type": "indicator",
        "id": "indicator--61c71841-c01a-493f-bf23-a36a5dcb0675"
      },
      {
        "name": "Teddy Bear",
        "created": "2019-06-24T04:43:32.713Z",
        "labels": [
          "nation-state"
        ],
        "resource_level": "government",
        "modified": "2019-06-24T04:43:32.713Z",
        "goals": [
          "compromising environment NGOs",
          "water-hole attacks geared towards energy sector"
        ],
        "sophistication": "innovator",
        "type": "threat-actor",
        "id": "threat-actor--c7477a20-4f53-46a0-87dd-53bf7f221fc9"
      },
      {
        "valid_from": "2019-06-24T04:43:32.713978Z",
        "name": "File hash for malware variant",
        "created": "2019-06-24T04:43:32.713Z",
        "pattern": "[file:hashes.md5 = 'd41d8cd98f00b204e9800998ecf8427e']",
        "labels": [
          "malicious-activity"
        ],
        "modified": "2019-06-24T04:43:32.713Z",
        "type": "indicator",
        "id": "indicator--9d29e11f-b86c-4d9d-b83a-98bdea0ab0f7"
      }
    ],
    "type": "bundle",
    "id": "e6073e5d-1473-4271-b27c-8c033cf8708f"
  }

when i add this data and try to fetch by id :e6073e5d-1473-4271-b27c-8c033cf8708f it does not give any data 

please let me knoe if i have made any mistake.

**Comment by clenk** [comment]
Hi @dipenpatel235, Bundles are not permanent and aren't stored in the TAXII server, just the objects inside it. So you can fetch any of the objects from that bundle, but not the bundle itself. If you just want to get all the objects on the server, you can use `collection.get_objects()`.

Also, `e6073e5d-1473-4271-b27c-8c033cf8708f` is an invalid id in stix. It should include the type, like: `bundle--e6073e5d-1473-4271-b27c-8c033cf8708f`. How was this content generated?

**Comment by dipenpatel235** [comment]
Thank you @clenk, I have succesfully fetch object.
