### ISSUE TITLE
Get objects by paging (Range in header)

### ISSUE THREAD

**Issue by thangld322** [oasis-open/cti-taxii-client#60]
Hi,
I see there are two ways of getting objects in TAXII. One is by passing added_after on, another is by adding Range to header like this: `curl -k -H "Range: items 100-150" --user <user:pass> <domain>/api/v1/taxii2/ti/collections/<collection-id>/objects/?added_after=2019-01-01T00:29:09.002Z`
My question is how can I use this library to get objects by Range? Thanks!

**Comment by emmanvg** [comment]
@thangld322 now you will be able to perform pagination requests via the `as_pages` method which acts like a generator:

``` python
   from taxii2client.v20 import Collection, as_pages

   collection = Collection('https://example.com/api1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116')

   # For pagination requests.
   for bundle in as_pages(collection.get_objects, per_request=50):
       print(bundle)

   # If you want to start at item X you can...
   for bundle in as_pages(collection.get_objects, start=100, per_request=50):
       print(bundle)
```
