### ISSUE TITLE
Unable to connect to the url : https://cti-taxii.mitre.org/taxii/ for server discovery

### ISSUE THREAD

**Issue by kannanraju1979** [oasis-open/cti-taxii-client#70]
Hi,
I using the cti-taxii-client for the first time inorder to subscribe to a taxii 2.x version of feed . I have the cti-taxii-client installed on my linux and used the following python script to connect to the https://cti-taxii.mitre.org/taxii/ feed - as described in  one of the blogs.. https://www.mitre.org/capabilities/cybersecurity/overview/cybersecurity-blog/attck%E2%84%A2-content-available-in-stix%E2%84%A2-20-via

# Instantiate server and get API Root
server = Server("https://cti-taxii.mitre.org/taxii/")
api_root = server.api_roots[0]

But while trying to connect i am getting :
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: https://cti-taxii.mitre.org/taxii/

But this URL seems to be working fine.. Would like to get some help with the taxii client onhow to connect tothe taxii2 feeds
Appreciate your time

**Comment by kannanraju1979** [comment]
i saw this wasalready replied in closed issues page.. thanks

**Comment by emmanvg** [comment]
Related #66
