### ISSUE TITLE
verify=False does not work

### ISSUE THREAD

**Issue by derekzhouzhili** [oasis-open/cti-taxii-client#88]
Hi,

I am using taxii2_client-2.2.2.dist-info and find that verify=False does not work. I am using self-sign certificate on https://192.168.129.141/taxii/:
`from taxii2client.v20 import Server
server_dst = Server('https://192.168.129.141/taxii/', user='username', password='password',
                    verify=False)`

It looks like it is because in sessions.py:request (line 463), it uses another verify rather than self.verify. As a result, verify=None and the verify=False passed does not take effect.

I can resolve the issue if add "verify=False" in line 543 of sessions.py:

`    def get(self, url, **kwargs):
        r"""Sends a GET request. Returns :class:`Response` object.

        :param url: URL for the new :class:`Request` object.
        :param \*\*kwargs: Optional arguments that ``request`` takes.
        :rtype: requests.Response
        """

        kwargs.setdefault('allow_redirects', True)
        return self.request('GET', url, verify=False, **kwargs)`

**Comment by derekzhouzhili** [comment]
better to change line 543 of sessions.py to:

`return self.request('GET', url, verify=self.verify, **kwargs)`

**Comment by zrush-mitre** [comment]
Hi @derekzhouzhili,

I'm a little confused about your issues post in a lot of different ways:

- The default medallion servers included in the taxii-server repo do not support SSL. Are you using a different server implementation to achieve an SSL connection?
- The suggested fixes in your post pertain to changing the code of the _requests_ python module, which the taxii-client inherits. We do not manage that codebase, so your suggestion would have to be sent to the code maintainers of that library, or a fix would need to be suggested within the code contained in this repo.
- The lines you mention for your recommendations are not consistent with the code found at the most updated version of the file [here](https://github.com/psf/requests/blob/master/requests/sessions.py). Are you sure you are using the correct version of the requests module?

Beyond all this, in my simple testing, the code pertaining to the (non-)verification of SSL certs seems to be working correctly. If you could give me more details about your environment, I may be able to replicate the bug on my end.

Thanks.

**Comment by emmanvg** [comment]
I will close this issue, its either referring to the `requests` library (in that case the issue should be opened in that [repo](https://github.com/psf/requests)) or a problem with the `taxii2-client` but its lacking details. Feel free to reopen if the problem has not been addressed.
