### ISSUE TITLE
taxii2 polling issue     need help

### ISSUE THREAD

**Issue by itsnotabhi** [oasis-open/cti-taxii-client#92]
I am new here, and confused about polling from taxii servers
I can't find any relevant documentation for polling from a remote server
Please guide me further and thanks

**Comment by clenk** [comment]
Hi @itsnotabhi, you can find documentation on how to use the TAXII client [in our readme](https://github.com/oasis-open/cti-taxii-client#usage). The example code there shows you how to make a connection to a TAXII server and get a collection. Once you have the collection you can call its `get_object()` or `get_objects()` method to access the objects in that collection.

If you need more information on TAXII 2 in general, you can find that [here](https://oasis-open.github.io/cti-documentation/taxii/intro). Note that the latest version of the TAXII specification, version 2.1, supports collections but not channels yet.

If you have more specific questions after reading some documentation, we'd be happy to help!

**Comment by emmanvg** [comment]
It sounds like the question has been answered. Feel free to re-open if you if you feel it has not been addressed.
