### ISSUE TITLE
add an option to set verification of ssl certificate to true or false

### ISSUE THREAD

**Issue by NetEyes** [oasis-open/cti-taxii-client#96]
Can you add an option to set verification of ssl certificate to true or false?
requests.get(url, verify=False)

**Comment by emmanvg** [comment]
Hi @NetEyes this option already exists and is exposed on all API classes. Perhaps you are running an older version of the library?

Example in its internal representation using requests:
https://github.com/oasis-open/cti-taxii-client/blob/3ee5574c620868fce25aa32222a17343f465b06b/taxii2client/common.py#L222-L242

Example in Collection class:
https://github.com/oasis-open/cti-taxii-client/blob/3ee5574c620868fce25aa32222a17343f465b06b/taxii2client/v21/__init__.py#L190-L218

**Comment by emmanvg** [comment]
``` python
# Performing TAXII 2.1 Requests
from taxii2client.v21 import Collection

collection = Collection(
    'https://example.com/api1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116',
    user='user',
    password='pass',
    verify=False
)
collection.get_object('indicator--252c7c11-daf2-42bd-843b-be65edca9f61')
```

**Comment by emmanvg** [comment]
Feel free to re-open if you think the issue has not been addressed.
