### ISSUE TITLE
406 Errors even after specifying correct library

### ISSUE THREAD

**Issue by maverickvn360** [oasis-open/cti-taxii-client#99]
Hello team,
By simply using the code in the first example of this [web page](https://www.mitre.org/capabilities/cybersecurity/overview/cybersecurity-blog/attck%E2%84%A2-content-available-in-stix%E2%84%A2-20-via): I got the 406 error.

Watching the previous issues, I made doubly sure I'm using the correct version of taxii2client:
`from taxii2client.v21 import Server`

Code:
```
        for url in urls:
            server = ""
            if not url.endswith('/taxii2/') or url.endswith('/taxii2'):
                server = Server(url=url+'/taxii2/')
            elif url.endswith('/taxii2'):
                server = Server(url=url+'/')
            else:
                server = Server(url)
            if server.api_roots:
                # Do something
```

I think the error is in the line 748-752 of the code: [taxii2client/v21/__init__.py](https://github.com/oasis-open/cti-taxii-client/blob/master/taxii2client/v21/__init__.py), as the Server object is refreshed and the refresh method doesn't have appropriate "Accept" header.

I also tried modifying the headers protected member __conn_, but couldn't refresh the server properly.

Please let me know if the issue is correct, or my understanding is incorrect.. Thanks a lot 👍

**Comment by maverickvn360** [comment]
After debugging, found that the headers are the following internally:
```
{'User-Agent': 'taxii2-client/2.3.0',
'Accept': 'application/taxii+json;version=2.1'}
```
The error still pops up. I've used the following url: [MITRE TAXII2]('https://cti-taxii.mitre.org/taxii2/')

**Comment by zrush-mitre** [comment]
Hi @maverickvn360,

Can you try querying a different server with the TAXII client? Either starting a local TAXII server, or trying another publicly available server. I believe the server is the cause of the issue, and not the client itself.

Thanks,
Zach

**Comment by clenk** [comment]
I think that server uses TAXII 2.0, whereas you're importing the TAXII 2.1 version of the `Server` class. Can you see if using the 2.0 version helps (`from taxii2client.v20 import Server`)?

**Comment by maverickvn360** [comment]
Hey Zach,

Thanks for replying :)

Agreed.. I queried another open source server, the records are available
and I believe the same too..

Is there a forum I can raise the same question on?

**Comment by maverickvn360** [comment]
Nope, still the same @clenk.

**Comment by zrush-mitre** [comment]
Hi @maverickvn360,

I assume you tried using the fix @clenk suggested? That seemed to fix the issues on my end.

On the topic of the ATT&CK server, there are no plans on their side to transition to 2.1, so I doubt a transition like that would happen anytime soon.

Let me know if you're still having issues.

**Comment by maverickvn360** [comment]
I tried, using taxiiv20 as a server but failed consistently. I've currently
no idea what could be causing it..

Thanks for responding, I'll retry and let you know.. 👍

**Comment by zrush-mitre** [comment]
Here is my code that fixes the issue:

`from taxii2client.v20 import Server`
`s = Server("https://cti-taxii.mitre.org/taxii/")`
`print(s.title)`

If yours is different, post yours and I can see if there is an issue there.

**Comment by maverickvn360** [comment]
I'm importing urls from a xml file, and I used `https://cti-taxii.mitre.org/taxii2/`.. Seems, it was the only culprit..
Got the api root 🔥  🎉 
Also, did you get only one API root?

Thanks :)

**Comment by zrush-mitre** [comment]
Yes there is 1 API root and 4 collections.

**Comment by maverickvn360** [comment]
Thanks a lot @zrush-mitre @clenk..

Got it!

Closing this issue :)
